apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-auth-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/nadir/minilibvolume/auth"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-auth-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
