apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-auth
    spec:
      containers:
        - name: mysql
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-auth-secret
                  key: password
            - name: MYSQL_DATABASE
              value: lib_auth
          ports:
            - containerPort: 3306
              name: mysql-auth
          volumeMounts:
            - name: mysql-auth-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-auth-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-auth-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-auth-service
spec:
  selector:
    app: mysql-auth
  ports:
    - protocol: TCP
      port: 3306
