package constant

const (
	LOG_TOPIC = "logs"
)

const (
	AUTH_DB_USERNAME = "AUTH_DB_USERNAME"
	AUTH_DB_PASSWORD = "AUTH_DB_PASSWORD"
	AUTH_DB_NAME     = "AUTH_DB_NAME"
	AUTH_DB_HOST     = "AUTH_DB_HOST"
	AUTH_DB_PORT     = "AUTH_DB_PORT"
)

const (
	BOOK_DB_USERNAME = "BOOK_DB_USERNAME"
	BOOK_DB_PASSWORD = "BOOK_DB_PASSWORD"
	BOOK_DB_NAME     = "BOOK_DB_NAME"
	BOOK_DB_HOST     = "BOOK_DB_HOST"
	BOOK_DB_PORT     = "BOOK_DB_PORT"
)

const (
	RENT_DB_USERNAME = "RENT_DB_USERNAME"
	RENT_DB_PASSWORD = "RENT_DB_PASSWORD"
	RENT_DB_NAME     = "RENT_DB_NAME"
	RENT_DB_HOST     = "RENT_DB_HOST"
	RENT_DB_PORT     = "RENT_DB_PORT"
)

const (
	LOG_MONGO_URI = "LOG_MONGO_URI"
	LOG_DB_NAME   = "LOG_DB_NAME"
)
