apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
        - name: logging
          image: nadirbasalamah/logging-service:v1
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
spec:
  selector:
    app: logging
  ports:
    - protocol: TCP
      port: 8085
