apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-book-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-book
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-book
    spec:
      containers:
        - name: mysql
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-book-secret
                  key: password
            - name: MYSQL_DATABASE
              value: lib_book
          ports:
            - containerPort: 3306
              name: mysql-book
          volumeMounts:
            - name: mysql-book-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-book-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-book-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-book-service
spec:
  selector:
    app: mysql-book
  ports:
    - protocol: TCP
      port: 3306
