apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-book-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/nadir/minilibvolume/book"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-book-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
