// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: rent.proto

package rent_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    int32  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId    int32  `protobuf:"varint,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BookTitle string `protobuf:"bytes,4,opt,name=book_title,json=bookTitle,proto3" json:"book_title,omitempty"`
}

func (x *Rent) Reset() {
	*x = Rent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rent) ProtoMessage() {}

func (x *Rent) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rent.ProtoReflect.Descriptor instead.
func (*Rent) Descriptor() ([]byte, []int) {
	return file_rent_proto_rawDescGZIP(), []int{0}
}

func (x *Rent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Rent) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Rent) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *Rent) GetBookTitle() string {
	if x != nil {
		return x.BookTitle
	}
	return ""
}

type GetAllRentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetAllRentsRequest) Reset() {
	*x = GetAllRentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRentsRequest) ProtoMessage() {}

func (x *GetAllRentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRentsRequest.ProtoReflect.Descriptor instead.
func (*GetAllRentsRequest) Descriptor() ([]byte, []int) {
	return file_rent_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllRentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllRentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rent *Rent `protobuf:"bytes,1,opt,name=rent,proto3" json:"rent,omitempty"`
}

func (x *GetAllRentsResponse) Reset() {
	*x = GetAllRentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRentsResponse) ProtoMessage() {}

func (x *GetAllRentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRentsResponse.ProtoReflect.Descriptor instead.
func (*GetAllRentsResponse) Descriptor() ([]byte, []int) {
	return file_rent_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllRentsResponse) GetRent() *Rent {
	if x != nil {
		return x.Rent
	}
	return nil
}

type CreateRentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId    int32  `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BookTitle string `protobuf:"bytes,3,opt,name=book_title,json=bookTitle,proto3" json:"book_title,omitempty"`
}

func (x *CreateRentRequest) Reset() {
	*x = CreateRentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRentRequest) ProtoMessage() {}

func (x *CreateRentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRentRequest.ProtoReflect.Descriptor instead.
func (*CreateRentRequest) Descriptor() ([]byte, []int) {
	return file_rent_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRentRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateRentRequest) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *CreateRentRequest) GetBookTitle() string {
	if x != nil {
		return x.BookTitle
	}
	return ""
}

type CreateRentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Rent    *Rent  `protobuf:"bytes,3,opt,name=rent,proto3" json:"rent,omitempty"`
}

func (x *CreateRentResponse) Reset() {
	*x = CreateRentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRentResponse) ProtoMessage() {}

func (x *CreateRentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRentResponse.ProtoReflect.Descriptor instead.
func (*CreateRentResponse) Descriptor() ([]byte, []int) {
	return file_rent_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateRentResponse) GetRent() *Rent {
	if x != nil {
		return x.Rent
	}
	return nil
}

var File_rent_proto protoreflect.FileDescriptor

var file_rent_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x04,
	0x52, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x2d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x72,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x52, 0x65, 0x6e, 0x74,
	0x52, 0x04, 0x72, 0x65, 0x6e, 0x74, 0x22, 0x64, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x61, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x72, 0x65, 0x6e, 0x74, 0x32,
	0x80, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x13,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x67, 0x65, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rent_proto_rawDescOnce sync.Once
	file_rent_proto_rawDescData = file_rent_proto_rawDesc
)

func file_rent_proto_rawDescGZIP() []byte {
	file_rent_proto_rawDescOnce.Do(func() {
		file_rent_proto_rawDescData = protoimpl.X.CompressGZIP(file_rent_proto_rawDescData)
	})
	return file_rent_proto_rawDescData
}

var file_rent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rent_proto_goTypes = []interface{}{
	(*Rent)(nil),                // 0: Rent
	(*GetAllRentsRequest)(nil),  // 1: GetAllRentsRequest
	(*GetAllRentsResponse)(nil), // 2: GetAllRentsResponse
	(*CreateRentRequest)(nil),   // 3: CreateRentRequest
	(*CreateRentResponse)(nil),  // 4: CreateRentResponse
}
var file_rent_proto_depIdxs = []int32{
	0, // 0: GetAllRentsResponse.rent:type_name -> Rent
	0, // 1: CreateRentResponse.rent:type_name -> Rent
	1, // 2: RentService.GetAllRents:input_type -> GetAllRentsRequest
	3, // 3: RentService.CreateRent:input_type -> CreateRentRequest
	2, // 4: RentService.GetAllRents:output_type -> GetAllRentsResponse
	4, // 5: RentService.CreateRent:output_type -> CreateRentResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rent_proto_init() }
func file_rent_proto_init() {
	if File_rent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rent_proto_goTypes,
		DependencyIndexes: file_rent_proto_depIdxs,
		MessageInfos:      file_rent_proto_msgTypes,
	}.Build()
	File_rent_proto = out.File
	file_rent_proto_rawDesc = nil
	file_rent_proto_goTypes = nil
	file_rent_proto_depIdxs = nil
}
